return {
    { 'hynek/vim-python-pep8-indent' },
    { 'airblade/vim-gitgutter' },
    { 'lvht/tagbar-markdown' },
    { 'tpope/vim-fugitive', tag = 'v3.7' },
    { 'cohama/lexima.vim' },
    { 'vim-scripts/argtextobj.vim' },
    { 'scrooloose/nerdtree' },
    { 'habamax/vim-sendtoterm' },
    { 'tpope/vim-surround' },
    { 'tpope/vim-commentary' },
    { 'lifepillar/vim-solarized8' },
    { 'vim-airline/vim-airline' },
    { 'vim-airline/vim-airline-themes' },
    { 'kien/ctrlp.vim' },
    { 'chrisbra/NrrwRgn' },
    { 'pangloss/vim-javascript' },
    { 'mxw/vim-jsx' },
    { 'justinmk/vim-sneak' },
    { 'nvie/vim-flake8' },
    { 'joukevandermaas/vim-ember-hbs' },
}
